# https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
# https://youtu.be/uFgcCL3t_JM?t=8207

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70 # com 70 % de CPU ele cria outro pod, também é possivel criar um para criar novos workers no cluster